name: workout_logger
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  auto_route: ^1.0.2
  basic_utils: ^3.0.2
  built_collection: ^5.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0
  easy_localization: ^3.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^6.0.0
  flutter_hooks: ^0.16.0
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^0.4.0
  freezed_annotation: ^0.14.1
  hooks_riverpod: ^0.14.0+2
  intl: ^0.17.0
  json_annotation: ^4.0.1
  moor: ^4.2.1
  moor_db_viewer: ^3.0.1
  path: ^1.8.0
  path_provider: ^2.0.1
  plugin_platform_interface: ^2.0.0
  rxdart: ^0.26.0
  sqlite3_flutter_libs: ^0.4.1
  stack: ^0.2.1
  uuid: ^3.0.4
  validators: ^3.0.0

dev_dependencies:
  auto_route_generator: ^1.0.2
  build_runner: ^1.12.2
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+2
  json_serializable: ^4.1.1
  lint: ^1.5.3
  mockito: ^5.0.5
  moor_generator: ^4.2.2

flutter:
  assets:
    - assets/data/
    - assets/translations/
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-BoldItalic.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-LightItalic.ttf
